### ISSUE TITLE
Add support for python remote file download

### ISSUE THREAD

**Issue by regadas** [spotify/flink-on-k8s-operator#177]

**Comment by JSchulte01** [comment]
@regadas I was adapting the current master branch docs for running with a remote job with python (downloading using an init container) but I'm running into an issue. 

#181 added an entrypoint which downloads remote files at startup - this included the JobSubmitter pod which is generated using the same image.

#279 removed the entrypoint script to do this download. I fully agree with the reasoning behind why it was removed.

However it seems when the JobSubmitter runs it executes a command referencing a python file which is not actually available on the JobSubmitter. I believe the JobSubmitter tries to copy the non-existent file across to the JobManager which obviously fails.

**Comment by regadas** [comment]
@JSchulte01 sorry for the late are you still having issues?

Remote files are now downloaded using init containers can you try using this new approach? I'll be closing this issue for the time being. Please reopen or create a new one if you are still having issues.

**Comment by JSchulte01** [comment]
Hey @regadas - no worries,

I think the problem is still extant with PyFlink - but I've moved away from pyflink to Scala Flink now so I'm not to troubled by closing the issue - I think the root cause is a difference in behaviour between pyflink and flink job submissions - so it's really an upstream problem.
