### ISSUE TITLE
OperatorHub and OLM version planned?

### ISSUE THREAD

**Issue by shalberd** [spotify/flink-on-k8s-operator#369]
Hello

Is there anything on the roadmap regarding making available your operator on Operator Hub and having it managed via Operator Lifecycle Manager (OLM)? I am asking in an openshift 4.8 / 4.9 Context, Kubernetes 1.22.

From an ops perspective, I find it strange that e.g. the Google Cloud platform version of the operator is not maintained.

Are there any plans to involve Google and especially RedHat more to make flink on K8s / openshift 4.9 truly production-ready? 
I am talking about financial services, medical services here.

**Comment by afilipchik** [comment]
I'm also curious whether it is alive as I had hard times getting connected with the author and there is only 1 maintainer. We are looking into moving out of Lyft's operator, and it seems like one from Google is dead. 

There is a new one from Apple under the Apache roof as well, I'm starting to think it will have a better feature.

**Comment by shalberd** [comment]
Hello Alex: Very nice indeed. I think both users and developers should focus on that one

https://flink.apache.org/news/2022/04/03/release-kubernetes-operator-0.1.0.html

https://github.com/apache/flink-kubernetes-operator

**Comment by regadas** [comment]
Hello, Thanks for bringing this up!

> Is there anything on the roadmap regarding making available your operator on Operator Hub and having it managed via Operator Lifecycle Manager (OLM)? I am asking in an openshift 4.8 / 4.9 Context

There are no plans since we don't use openshift. However, if the community is interested and it's willing to help we can make it happen.

> From an ops perspective, I find it strange that e.g. the Google Cloud platform version of the operator is not maintained.

The reason is unclear to us as well and several attempts were made through the community to clarify what was going on but not avail. That's this fork started! In a way I'm actually happy with it because it allows us to move faster and add the features we need. 

We (Spotify) are using this for production use cases and even though there's still a lot to be done we will continue to work on this project. We do have some new upcoming work planned to better support batch and streaming use cases. On a side note, it might seem just one dev backing this up, but there's a team 😄

The apache project is still fairly new and it will take some time to catch up to our needs plus we will lack in some way the ability to move fast.

With that said, it will be up to the user to decide which flavor suits better their needs right now.

Thanks!

**Comment by shalberd** [comment]
Yes, or go with a product like Ververica, if production-readiness and commercial support is needed.

**Comment by shalberd** [comment]
Thank you for your feedback, it helped surveying the landscape and possibilities.
