### ISSUE TITLE
Do not validate missing CPU(and memory) limits

### ISSUE THREAD

**Issue by AndersBennedsgaard** [spotify/flink-on-k8s-operator#383]
I just tried to remove the CPU limits on my `FlinkCluster` due to some severe throttling, but unfortunately the operator adds a check for non-zero CPU and memory limits.
In my mind, this is not a responsibility of the operator to check resource limits and requests, as you could just add a `ResourceQuota` (and a `LimitRange`) to ensure this.

Many recommends not using CPU limits in your pods, since Kubernetes will throttle anything that has a non-zero limit. The worry of not using the CPU limits, is that other pods might have their performance affected from a single instance running wild, but if you remember to add CPU requests to your pods they will always have enough to run.

**Comment by regadas** [comment]
Hi @AndersBennedsgaard,
The operator right now enforces `limits` simply because it's used to derive the proper values to some of the Flink properties in order to get a properly sized Flink cluster.

I was reading up a bit more on this topic and throttling seems to be a thing even when pods are configured to `Guaranteed QoS`. Just to confirm, were you setting it to have this `QoS` class?

Nevertheless, I think a good change here would be to rely on the `requests` if `limits` are not set.

**Comment by AndersBennedsgaard** [comment]
@regadas sorry for not replying sooner, but no, I was not setting that QoS class.
I agree with using requests when limits are not set. If neither are used, then the validation could fail

**Comment by regadas** [comment]
So yeah even with requests/limits set to the same value (QoS class Guranteed) there's CPU throttling.
