### ISSUE TITLE
Question: is the latest CRD backwards compatible with the CRD from 0.30

### ISSUE THREAD

**Issue by perlow** [spotify/flink-on-k8s-operator#701]
Hi, we are trying to upgrade a flink cluster that is currently using the v0.30 of the operator. We want to be able to easily revert back to 0.30 if something goes wrong with the upgrade. We wanted to check if we can first upgrade the CRD without breaking the current deployment. Does the latest CRD contain any backwards incompatible changes that would prevent us from taking this approach?

**Comment by jto** [comment]
Hey!
As far as I know, we never broke back compatibility. Is that correct @regadas ?

**Comment by regadas** [comment]
Hello!

I think, CRD should be backwards compatible. I was going through the releases and nothing stood out. We tried to be back compat even for our use case but since it's a big jump taking some caution doesnt hurt. 

That said, one thing you need to pay attention too is that the latest version requires a fairly recent k8s version.

Feel free to let us know how the upgrade goes and drop an issue if you find some bugs.

**Comment by perlow** [comment]
Thank you!
